name: Frontend PR Tests

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint
      
    - name: Run TypeScript type checking
      run: npm run typecheck
    
    


