name: Run tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node/@v2
      with:
        node-version: 18.16
    - name: Install Dependencies
      run: npm ci
    # - name: Lint Code Base
    #   uses: github/super-linter@v2
    # - name: Build
    #   run: npm run build
